<?php

namespace Magento2Store\Hellogrid\Model;

class Post extends \Magento\Framework\Model\AbstractModel implements \Magento\Framework\DataObject\IdentityInterface
{

    const CACHE_TAG = 'hellogrid_post';
    protected $_cacheTag = 'hellogrid_post';
    protected $_eventPrefix = 'hellogrid_post';

    protected function _construct()
    {
        $this->_init('Magento2Store\Hellogrid\Model\ResourceModel\Post');
        parent::_construct(); // TODO: Change the autogenerated stub
    }

    public function getIdentities()
    {
        return [self::CACHE_TAG . '_' . $this->getId()];
    }

    public function getDefaultValues()
    {
        $values = [];
        return $values;
    }
}